### ISSUE TITLE
Possible crash on restore of config when event filter is enabled

### ISSUE THREAD

**Issue by alja** [alja/FireworksWeb#48]
MAIN parse arguments [cmsShowWeb.exe] [-c] 
Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FW2Main.cc:251 in void FW2Main::parseArguments(int, char**)>: :Config https://fireworks.cern.ch/config/amraktad/rec.fwc

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FW2Main.cc:281 in void FW2Main::parseArguments(int, char**)>: :Input root://cmsxrootd.fnal.gov:1094//store/user/alja/demo.root

Info in <TGeoManager::TGeoManager>: Geometry Geometry, default geometry created
Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/CmsShowNavigator.cc:119 in bool CmsShowNavigator::appendFile(const string&, bool, bool)>: :CmsShowNavigator::appendFile [root://cmsxrootd.fnal.gov:1094//store/user/alja/demo.root]

Warning in <[ROOT.Eve] Warning /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:94 in void FWGeometry::applyGlobalTag(const string&)>: :Could not guess geometry from global tag.  Using geometry scenario 2021.

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:98 in void FWGeometry::applyGlobalTag(const string&)>: :Guessed geometry cmsGeom2021.root from global tag gt_undef

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:184 in void FWGeometry::loadMap(const char*)>: :Load idToGeo 2021 from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/src/Fireworks/Geometry/data/cmsGeom2021.root

Error in <[ROOT.Eve] Error /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FW2Main.cc:433 in void FW2Main::setupConfiguration()>: :Unable to load configuration file 'https://fireworks.cern.ch/config/amraktad/rec.fwc': Bad tag

**Comment by alja** [comment]
MAIN parse arguments [cmsShowWeb.exe] [-c] 
Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FW2Main.cc:251 in void FW2Main::parseArguments(int, char**)>: :Config /var/www/html/config/amraktad/fireworks.fwc

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FW2Main.cc:281 in void FW2Main::parseArguments(int, char**)>: :Input root://cmsxrootd.fnal.gov:1094//store/user/alja/demo.root

Info in <TGeoManager::TGeoManager>: Geometry Geometry, default geometry created
Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/CmsShowNavigator.cc:119 in bool CmsShowNavigator::appendFile(const string&, bool, bool)>: :CmsShowNavigator::appendFile [root://cmsxrootd.fnal.gov:1094//store/user/alja/demo.root]

Warning in <[ROOT.Eve] Warning /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:94 in void FWGeometry::applyGlobalTag(const string&)>: :Could not guess geometry from global tag.  Using geometry scenario 2021.

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:98 in void FWGeometry::applyGlobalTag(const string&)>: :Guessed geometry cmsGeom2021.root from global tag gt_undef

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWGeometry.cc:184 in void FWGeometry::loadMap(const char*)>: :Load idToGeo 2021 from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/src/Fireworks/Geometry/data/cmsGeom2021.root

Warning in <[ROOT.Eve] Warning /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWTableViewManager.cc:217 in virtual void FWTableViewManager::setFrom(const FWConfiguration&)>: :no table column configuration stored, using defaults

Info in <[ROOT.Eve] Info /data2/alja/CMSSW_12_1_0_pre2_FWLITE-cms2/src/FireworksWeb/Core/src/FWFileEntry.cc:481 in void FWFileEntry::runCollectionFilter(FWFileEntry::Filter*, const FWEventItemsManager*, FWWebGUIEventFilter*, const CmsShowNavigator*)>: :FWFileEntry::runFilter Running filter patMuons_slimmedMuons__RECO.obj@.size()>3' for file 'root://cmsxrootd.fnal.gov//store/user/alja/demo.root'.

100 events took 445.000000 => stepsize 224
offset 100 result 1 seconds 491
offset 324 result 1 seconds 451
offset 548 result 3 seconds 417
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
Creating new holder
offset 772 result 3 seconds 606
offset 996 result 3 seconds 2
N selected 3
Creating new holder
Creating new holder
Creating new holder

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 8 (Thread 0x7f0800a11700 (LWP 3698815)):
#0  0x00007f08e1755a35 in pthread_cond_wait

GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f08928b0f9d in XrdSysCondVar::Wait() () from /data2/alja/customCmsBuilds/rep/slc7_amd64_gcc900/external/xrootd/4.12.3-llifpc2/lib64/libXrdUtils.so.2
#2  0x00007f0870abd6d8 in XrdCl::File::Read(unsigned long, unsigned int, void*, unsigned int&, unsigned short) () from /data2/alja/customCmsBuilds/rep/slc7_amd64_gcc900/external/xrootd/4.12.3-llifpc2/lib64/libXrdCl.so.2
#3  0x00007f08c503c310 in TNetXNGFile::ReadBuffer(char*, long long, int) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/lcg/root/root-install/lib/libNetxNG.so
#4  0x00007f08e45ec4f1 in TBasket::ReadBasketBuffers(long long, int, TFile*) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#5  0x00007f08e45f64b9 in TBranch::GetBasketImpl(int, TBuffer*) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#6  0x00007f08e45f6aad in TBranch::GetBasketAndFirst(TBasket*&, long long&, TBuffer*) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#7  0x00007f08e45f7397 in TBranch::GetEntry(long long, int) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#8  0x00007f08e4608e78 in TBranchElement::GetEntry(long long, int) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#9  0x00007f08e4608e1d in TBranchElement::GetEntry(long long, int) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#10 0x00007f08e4608e1d in TBranchElement::GetEntry(long long, int) () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/external/slc7_amd64_gcc900/lib/libTree.so
#11 0x00007f08e53540fc in fwlite::DataGetterHelper::getBranchData(edm::EDProductGetter const*, long long, fwlite::internal::Data&) const () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#12 0x00007f08e5356d76 in fwlite::DataGetterHelper::getByLabel(std::type_info const&, char const*, char const*, char const*, void*, long) const () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#13 0x00007f08e535c147 in fwlite::Event::getByLabel(std::type_info const&, char const*, char const*, char const*, void*) const () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#14 0x00007f08e535f174 in fwlite::EventBase::getByLabelImpl(std::type_info const&, std::type_info const&, edm::InputTag const&) const () from /home/viz/cmsShowWeb-1.8/slc7_amd64_gcc900/cms/fwlite/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#15 0x00007f08e5ee3c4d in bool edm::EventBase::getByLabel<edm::FWGenericObject>(edm::InputTag const&, edm::Handle<edm::FWGenericObject>&) const () from /home/viz/cmsShowWeb-1.8/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libFireworksWebCore.so
#16 0x00007f08e5ece40a in FWEventItem::data() const () from /home/viz/cmsShowWeb-1.8/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libFireworksWebCore.so
#17 0x00007f08e5ece846 in FWEventItemsManager::newEvent(edm::EventBase const*) () from /home/viz/cmsShowWeb-1.8/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libFireworksWebCore.so
#18 0x00007f08e5eb602b in FW2Main::draw_event() () from /home/viz/cmsShowWeb-1.8/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libFireworksWebCore.so
#19 0x00007f08e5eaf74d in CmsShowNavigator::runFilterThread() () from /home/viz/cmsShowWeb-1.8/CMSSW_12_1_0_pre2_FWLITE-cms2/lib/slc7_amd64_gcc900/libFireworksWebCore.so
#20 0x00007f08e1d52af0 in std::execute_native_thread_routine (__p=0x195cf710) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#21 0x00007f08e1751ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f08e14799fd in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7f085781a700 (LWP 3698756)):
